AllCops:
  DisabledByDefault: true
  Exclude:
    - "spec/**/*"

Lint/AmbiguousOperator:
  Enabled: true
  Severity: warning
Lint/AmbiguousRegexpLiteral:
  Enabled: true
  Severity: warning
Lint/AssignmentInCondition:
  Enabled: true
  Severity: warning
Lint/BlockAlignment:
  Enabled: true
  Severity: warning
Lint/CircularArgumentReference:
  Enabled: true
  Severity: warning
Lint/ConditionPosition:
  Enabled: true
  Severity: warning
Lint/DefEndAlignment:
  Enabled: true
  Severity: warning
Lint/DeprecatedClassMethods:
  Enabled: true
  Severity: warning
Lint/DuplicateCaseCondition:
  Enabled: true
  Severity: warning
Lint/DuplicateMethods:
  Enabled: true
  Severity: warning
Lint/DuplicatedKey:
  Enabled: true
  Severity: warning
Lint/EachWithObjectArgument:
  Enabled: true
  Severity: warning
Lint/ElseLayout:
  Enabled: true
  Severity: warning
Lint/EmptyEnsure:
  Enabled: true
  Severity: warning
Lint/EmptyExpression:
  Enabled: true
  Severity: warning
Lint/EmptyInterpolation:
  Enabled: true
  Severity: warning
Lint/EmptyWhen:
  Enabled: true
  Severity: warning
Lint/EndAlignment:
  Enabled: true
  Severity: warning
  EnforcedStyleAlignWith: start_of_line
Lint/EndInMethod:
  Enabled: true
  Severity: warning
Lint/EnsureReturn:
  Enabled: true
  Severity: warning
Lint/InheritException:
  Enabled: true
  Severity: warning
Lint/LiteralInCondition:
  Enabled: true
  Severity: warning
Lint/LiteralInInterpolation:
  Enabled: true
  Severity: warning
Lint/Loop:
  Enabled: true
  Severity: warning
Lint/MultipleCompare:
  Enabled: true
  Severity: warning
Lint/NestedMethodDefinition:
  Enabled: true
  Severity: warning
Lint/ParenthesesAsGroupedExpression:
  Enabled: true
  Severity: warning
Lint/RequireParentheses:
  Enabled: true
  Severity: warning
Lint/RescueException:
  Enabled: true
  Severity: warning
Lint/SafeNavigationChain:
  Enabled: true
  Severity: warning
Lint/ShadowingOuterLocalVariable:
  Enabled: true
  Severity: warning
Lint/StringConversionInInterpolation:
  Enabled: true
  Severity: warning
Lint/UnderscorePrefixedVariableName:
  Enabled: true
  Severity: warning
Lint/UnneededDisable:
  Enabled: true
  Severity: warning
Lint/UnneededSplatExpansion:
  Enabled: true
  Severity: warning
Lint/UnreachableCode:
  Enabled: true
  Severity: warning
Lint/UnusedMethodArgument:
  Enabled: true
  Severity: warning
Lint/UselessAssignment:
  Enabled: true
  Severity: warning
Lint/UselessComparison:
  Enabled: true
  Severity: warning
Lint/Void:
  Enabled: true
  Severity: warning

Metrics/LineLength:
  Enabled: true
  Severity: warning
  Max: 100
Metrics/ParameterLists:
  Enabled: true
  Severity: warning

Performance/Casecmp:
  Enabled: true
  Severity: warning
Performance/Count:
  Enabled: true
  Severity: warning
Performance/Detect:
  Enabled: true
  Severity: warning
Performance/DoubleStartEndWith:
  Enabled: true
  Severity: warning
Performance/EndWith:
  Enabled: true
  Severity: warning
Performance/FlatMap:
  Enabled: true
  Severity: warning
Performance/HashEachMethods:
  Enabled: true
  Severity: warning
Performance/RangeInclude:
  Enabled: true
  Severity: warning
Performance/RedundantBlockCall:
  Enabled: true
  Severity: warning
Performance/RedundantMatch:
  Enabled: true
  Severity: warning
Performance/RedundantMerge:
  Enabled: true
  Severity: warning
Performance/RegexpMatch:
  Enabled: true
  Severity: warning
Performance/ReverseEach:
  Enabled: true
  Severity: warning
Performance/Sample:
  Enabled: true
  Severity: warning
Performance/Size:
  Enabled: true
  Severity: warning
Performance/StartWith:
  Enabled: true
  Severity: warning
Performance/StringReplacement:
  Enabled: true
  Severity: warning
Performance/TimesMap:
  Enabled: true
  Severity: warning

Security/Eval:
  Enabled: true
  Severity: error
Security/JSONLoad:
  Enabled: true
  Severity: warning
Security/MarshalLoad:
  Enabled: true
  Severity: warning
Security/YAMLLoad:
  Enabled: true
  Severity: warning

Style/AccessorMethodName:
  Enabled: true
  Severity: warning
Style/AlignArray:
  Enabled: true
  Severity: warning
Style/AlignHash:
  Enabled: false
  Severity: warning
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Style/AlignParameters:
  Enabled: true
  Severity: warning
Style/AndOr:
  Enabled: true
  Severity: warning
Style/AsciiIdentifiers:
  Enabled: true
  Severity: warning
Style/Attr:
  Enabled: true
  Severity: warning
Style/AutoResourceCleanup:
  Enabled: true
  Severity: warning
Style/BeginBlock:
  Enabled: true
  Severity: warning
Style/BlockEndNewline:
  Enabled: true
  Severity: warning
Style/ClassAndModuleCamelCase:
  Enabled: true
  Severity: warning
Style/ClassMethods:
  Enabled: true
  Severity: warning
Style/ClassVars:
  Enabled: true
  Severity: warning
Style/ClosingParenthesisIndentation:
  Enabled: true
  Severity: warning
Style/ColonMethodCall:
  Enabled: true
  Severity: warning
Style/ConditionalAssignment:
  Enabled: true
  Severity: warning
Style/ConstantName:
  Enabled: true
  Severity: warning
Style/DefWithParentheses:
  Enabled: true
  Severity: warning
Style/DotPosition:
  Enabled: true
  Severity: warning
  EnforcedStyle: trailing
Style/EachForSimpleLoop:
  Enabled: true
  Severity: warning
Style/EachWithObject:
  Enabled: true
  Severity: warning
Style/ElseAlignment:
  Enabled: false
  Severity: warning
Style/EmptyCaseCondition:
  Enabled: true
  Severity: warning
Style/EmptyElse:
  Enabled: true
  Severity: warning
Style/EmptyLinesAroundAccessModifier:
  Enabled: true
  Severity: warning
Style/EmptyMethod:
  Enabled: true
  Severity: warning
Style/EndBlock:
  Enabled: true
  Severity: warning
Style/EvenOdd:
  Enabled: true
  Severity: warning
Style/FirstArrayElementLineBreak:
  Enabled: true
  Severity: warning
Style/FirstHashElementLineBreak:
  Enabled: true
  Severity: warning
Style/FirstMethodArgumentLineBreak:
  Enabled: true
  Severity: warning
Style/FirstMethodParameterLineBreak:
  Enabled: true
  Severity: warning
Style/FirstParameterIndentation:
  Enabled: true
  Severity: warning
Style/FlipFlop:
  Enabled: true
  Severity: warning
Style/For:
  Enabled: true
  Severity: warning
Style/FrozenStringLiteralComment:
  Enabled: true
  Severity: warning
Style/GlobalVars:
  Enabled: true
  Severity: error
Style/GuardClause:
  Enabled: true
  Severity: warning
Style/HashSyntax:
  Enabled: true
  Severity: warning
  EnforcedStyle: ruby19_no_mixed_keys
Style/IfInsideElse:
  Enabled: true
  Severity: warning
Style/IfUnlessModifier:
  Enabled: true
  Severity: warning
Style/IndentArray:
  Enabled: true
  Severity: warning
Style/IndentAssignment:
  Enabled: true
  Severity: warning
Style/IndentationConsistency:
  Enabled: true
  Severity: warning
Style/IndentationWidth:
  Enabled: true
  Severity: warning
Style/InfiniteLoop:
  Enabled: true
  Severity: warning
Style/InlineComment:
  Enabled: true
  Severity: warning
Style/LambdaCall:
  Enabled: true
  Severity: warning
Style/MethodCallWithArgsParentheses:
  Enabled: true
  Severity: warning
  IgnoredMethods:
    # require
    - require
    - require_relative
    # include, extend
    - include
    - extend
    # Class method calls
    - attr_reader
    - attr_writer
    - attr_accessor
    - alias_method
    - private_constant
    - private_class_method
    # Common debug
    - puts
    # error
    - raise
    - fail
    # Gems
    - Contract
    - memoize
    # RSpec
    - describe
    - context
    - it
    - to
    - to_not
    - not_to
    - should
    - should_not
    - it_behaves_like
Style/MethodCallWithoutArgsParentheses:
  Enabled: true
  Severity: warning
Style/MethodName:
  Enabled: true
  Severity: warning
Style/MultilineBlockLayout:
  Enabled: true
  Severity: warning
Style/MultilineMemoization:
  Enabled: true
  Severity: warning
Style/MutableConstant:
  Enabled: true
  Severity: warning
Style/NestedParenthesizedCalls:
  Enabled: true
  Severity: warning
Style/Next:
  Enabled: true
  Severity: warning
Style/NilComparison:
  Enabled: true
  Severity: warning
Style/NonNilCheck:
  Enabled: true
  Severity: warning
Style/Not:
  Enabled: true
  Severity: warning
Style/NumericLiterals:
  Enabled: true
  Severity: warning
Style/NumericPredicate:
  Enabled: true
  Severity: warning
Style/OpMethod:
  Enabled: true
  Severity: warning
Style/OptionHash:
  Enabled: true
  Severity: warning
Style/OptionalArguments:
  Enabled: true
  Severity: warning
Style/ParallelAssignment:
  Enabled: true
  Severity: warning
Style/RedundantBegin:
  Enabled: true
  Severity: warning
Style/RedundantFreeze:
  Enabled: true
  Severity: warning
Style/RedundantParentheses:
  Enabled: true
  Severity: warning
Style/RescueEnsureAlignment:
  Enabled: true
  Severity: warning
Style/SelfAssignment:
  Enabled: true
  Severity: warning
Style/StabbyLambdaParentheses:
  Enabled: true
  Severity: warning
Style/Tab:
  Enabled: true
  Severity: warning
Style/TrailingBlankLines:
  Enabled: true
  Severity: warning
Style/TrailingCommaInArguments:
  Enabled: true
  Severity: warning
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInLiteral:
  Enabled: true
  Severity: warning
  EnforcedStyleForMultiline: comma
Style/TrailingWhitespace:
  Enabled: true
  Severity: warning
Style/UnlessElse:
  Enabled: true
  Severity: warning
Style/VariableName:
  Enabled: true
  Severity: warning
Style/VariableNumber:
  Enabled: true
  Severity: warning
  EnforcedStyle: snake_case
Style/ZeroLengthPredicate:
  Enabled: true
  Severity: warning

Bundler/DuplicatedGem:
  Enabled: true
  Severity: warning
