Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingComma:
  # If EnforcedStyleForMultiline is comma, the cop requires a comma after the
  # last item of a list, but only for lists where each item is on its own line.
  # If EnforcedStyleForMultiline is consistent_comma, the cop requires a comma
  # after the last item of a list, for all lists.
  EnforcedStyleForMultiline: comma

Style/SignalException:
  EnforcedStyle: only_fail

# Multi-line method chaining should be done with leading dots.
Style/DotPosition:
  EnforcedStyle: trailing

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/PredicateName:
  Enabled: false
